apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-dev
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # Base64-encoded 'password'
  mysql-repl-password: cmVwbF9wYXNz # Base64-encoded 'repl_pass'
  mysql-user: dXNlcg== # Base64-encoded 'user'
  mysql-password: dXNlcl9wYXNzd29yZA== # Base64-encoded 'user_password'
